// Generated by https://quicktype.io
//Lo generamos con la extensión Paste as Code
//Copiamos el archivo JSON, luego Ctrl + Shift + P y buscamos Paste as Code y nombramos la interface.

export interface PokemonListResponse {
  count: number;
  next?: string;
  previous?: string;
  results: SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  url: string;
  id: number; //Se agrega
  img: string; // Se agrega
}
